yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.About.as_view(), name='author'),
    path('tech/', views.Tech.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'


urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('', views.index, name='index'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow')
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from core.models import CreatedModel


User = get_user_model()


class Group(models.Model):
    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField('Описание группы', max_length=400)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(CreatedModel):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['-pub_date']


class Comment(CreatedModel):
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст поста'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Пост',
        help_text='Пост, к которому относится комментарий',
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        help_text='Автор, написавший комментарий',
        related_name='comments'
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-pub_date']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписка на автора',
        related_name='following'
    )

    def __str__(self):
        return f'{self.user.username} follow {self.author.username}'

    constraints = [
        models.UniqueConstraint(
            fields=['user', 'author'], name='unique_author_user_following'
        )
    ]

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': 'Текст поста', 'group': 'Сообщество',
                  'image': 'Фото поста'}

    def clean_text(self):
        data = self.cleaned_data['text']

        if not data:
            raise forms.ValidationError('Поле не должно быть пустым!')

        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Текст комментария'}
        help_text = 'Напишиште ваше мнение о посте'

    def clean_text(self):
        data = self.cleaned_data['text']

        if not data:
            raise forms.ValidationError('Поле не должно быть пустым!')
        return data

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Post, Group, Follow
from django.shortcuts import redirect
from django.contrib.auth import get_user_model
from .forms import PostForm, CommentForm
from .utils import paginate_page


User = get_user_model()


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.select_related('group').all()
    page_obj = paginate_page(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.post_set.all()
    posts_count = posts.count()
    page_obj = paginate_page(request, posts)
    context = {
        'page_obj': page_obj,
        'group': group,
        'posts_count': posts_count
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    posts_count = posts.count()
    following = False
    if request.user.is_authenticated:
        if Follow.objects.filter(
            user=request.user, author=author
        ):
            following = True
    page_obj = paginate_page(request, posts)
    context = {
        'page_obj': page_obj,
        'posts_count': posts_count,
        'author': author,
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'comments': comments,
        'form': form
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/post_create.html'
    is_edit = False
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('posts:profile', post.author)
    return render(request, template, {'form': form, 'is_edit': is_edit})


@login_required
def post_edit(request, post_id):
    template = 'posts/post_create.html'
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': is_edit,
        'post': post
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(
        request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = paginate_page(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        follow = Follow.objects.filter(user=request.user, author=author)
        if not follow.exists():
            follow = Follow.objects.create(user=request.user, author=author)
            follow.save()
            return redirect('posts:follow_index')
    return redirect('posts:index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow = get_object_or_404(Follow, user=request.user, author=author)
    follow.delete()
    return redirect('posts:index')

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title%}
  Подписки
{% endblock %}

{% block content %}
{% include 'posts/includes/switcher.html' %}
  <div class="container py-5">        
  <h1>Подписки </h1> 
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      {% if post.group %}   
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  <h1>{{ group.title }}</h1>
{% endblock %}

{% block content %}
  <div class="container py-5">        
    <h1>Записи сообщества: {{ group.title }} </h1>
    <p>{{ group.description }}</p>
    <h3>Всего постов: {{ posts_count }} </h3>   
    {% for post in page_obj %}
    {% include 'posts/includes/post_list.html' %}
      {% if not forloop.last %}
        <hr>
      {% endif %}     
    {%endfor%}
    </div>  
  
  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title%}
  Последние обновления на сайте
{% endblock %}

{% block content %}
{% include 'posts/includes/switcher.html' %}
  <div class="container py-5">        
  <h1>Последние обновления на сайте </h1> 
  {% load cache %}
    {% cache 20 page_obj page_obj.number %}
      {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}
        {% if post.group %}   
          <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% endcache %}    
  </div>
  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}

{% block title%}
  {% if is_edit %}
    Редактировать пост
  {% else %}  
    Новый пост
  {% endif %}  
{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
              Редактировать запись
            {% else %}  
              Добавить запись
            {% endif %}               
          </div>
          <div class="card-body">        
            {% if is_edit %}
            <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post.id %}">
            {% else %} 
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create'%}">
            {% endif %}   
              {% csrf_token %}        
              <div class="form-group row my-3 p-3">
                {% if is_edit %}
                  <label for="id_text">
                    Текст поста                  
                    <span class="required text-danger" >*</span>                  
                  </label>
                  <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                    {{ post.text }}
                  </textarea>
                {% endif %}
                {% for field in form %} 
                  <div class="form-group row my-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                        {% if field.required %}
                          <span class="required text-danger">*</span>
                        {% endif %}
                    </label>
                    {{ field }}
                    {% if field.help_text %}
                      <small 
                        id="{{ field.id_for_label }}-help"
                        class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                {% endfor %}                             
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}  
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %} 

{% block title%}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{%block content%} 
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}   
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              <a href="{% url 'posts:group_posts' post.group.slug %}">
                все записи группы
              </a>
            </li>
            {% endif %} 
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                Все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
           {{post.text}}
          </p>
          {% if post.author == user %}  
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
                Редактировать запись
            </a>
          {% endif %}   
          {% if user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}"> 
                  {% csrf_token %}
                  {% load user_filters %}     
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>
          {% endif %}
          {% for comment in comments %}
            <div class="media mb-4">
              <div class="media-body">
                <h5 class="mt-0">
                  <a href="{% url 'posts:profile' comment.author.username %}">
                    {{ comment.author.username }}
                  </a>
                </h5>
                <p>
                  {{ comment.text }}
                </p>
              </div>
            </div>
          {% endfor %}                           
        </article>
      </div> 
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title%}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}

{%block content%}    
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name}} </h1>
        <h3>Всего постов: {{ posts_count }} </h3>
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>  
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
        {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}
          {% if post.group %}   
              <a href="{% url 'posts:group_posts' post.group.slug %}">
                все записи группы {{post.group.title}}
              </a>
          {% endif %}       
          {% if not forloop.last %}
            <hr>
          {% endif %} 
        {% endfor %}  
      </div>   

  {% include 'posts/includes/paginator.html' %}

{%endblock%}